### PR TITLE
fix(BaseStatusListFragment): save scroll position when adding quote

### PR DESCRIPTION
**Pull request by FineFindus**
Partially fixes an issue, where the recylcerview would be reset back to the top when adding a quote. With this it only lags/stutters. A full fix would be better, but I honestly have no idea how to.

### CODE REVIEW

**Comment by LucasGGamerM** [comment]
I think this is not optional, as it will jump whenever a new quote it added. Maybe a check would be nicer here

**Comment by FineFindus** [comment]
> as it will jump whenever a new quote it added

Yes, that's the point of it, though the jump is only noticeable as a small lag. I'm not quite sure what you mean by adding a check?

**Comment by LucasGGamerM** [comment]
> > as it will jump whenever a new quote it added
> 
> Yes, that's the point of it, though the jump is only noticeable as a small lag. I'm not quite sure what you mean by adding a check?

It is to check if the position changed to zero, *then* we would go back to the position.

**Comment by FineFindus** [comment]
That wouldn't matter, since it will always reset to be 0 when a non-official quote is loaded and added.

**Comment by LucasGGamerM** [comment]
> That wouldn't matter, since it will always reset to be 0 when a non-official quote is loaded and added.

No, not really. The RecyclerView's adapter updates, but the position is kept consistent. What I mean by that is that the recycler view doesn't scroll to the top every time a new quote status is added.

**Comment by FineFindus** [comment]
Proper fix in 519cb672d2570bb098ce701a098d5d28731c6ef0, 1829dc1d9d70beabfc35bafb106c48e1f143f5d5 and 55ad624209b5e9c28a28f4ea38381d79cadd08aa.

**Pull request closed without merging**
