### PR TITLE
Add Android 13 monochrome icon

### PR DESCRIPTION
**Pull request by florian-obernberger**
Since I'm personally using Android 13 and like having apps with monochrome icons, I went ahead and added one in this PR.

To create the monochrome icon I've simple take the existing `ic_launcher_foreground.xml`, removed the background and the stroke of the "o".

If this icon is not to your liking, it can obviously be changed.

I also want to apologize if this PR is not to your liking – it's pretty much my first PR, but here you go!

### CODE REVIEW

**Comment by LucasGGamerM** [comment]
Thank you for your contribution! I for now dont have anywhere to test this on, but I will merge this soon!

**Comment by florian-obernberger** [comment]
If you'd like I can provide screenshots! I think by now you're also able to set up an Android 13 emulator through Android Studio. :D

**Comment by LucasGGamerM** [comment]
Please do share a screenshot! I am just waiting for calyxos to put the themed icon option. But I would love to see it!

**Comment by florian-obernberger** [comment]
Here is a screenshot, I hope it's good enough :D

Screenshot of Moshidon Logo

**Comment by LucasGGamerM** [comment]
Man! This looks perfect! I will merge it tomorrow, thank you!

**Comment by florian-obernberger** [comment]
Here is a screenshot, I hope it's good enough :D

Screenshot of Moshidon Logo

**Comment by florian-obernberger** [comment]
Fuck sorry, Im typing from my phone, I did not mean to close the PR, not even sure how I did it...

Anyways, I hope you don't mind that I deleted the outline of the o.

**Comment by LucasGGamerM** [comment]
It's alright. Idk what you mean by deleting the outline of the o though

**Comment by florian-obernberger** [comment]
The `ic_launcher_foreground.xml` defines a stroke color for the "o", essentially giving it an outline. You can barely see it on the logo though, since the stroke is pure black and kinds merges with the grey background.

**Comment by LucasGGamerM** [comment]
Ohh, I remember that, I did it by accident when designing the logo. Thankfully it's not noticeable at all, and your monochrome icon fits right in place!

**Comment by florian-obernberger** [comment]
You can always just remove the outline!

Oh and btw: I don't think you need to define the background color in the foreground icon! (The first path element)

**Comment by LucasGGamerM** [comment]
It's alright, I dont think I need to change it

**Comment by LucasGGamerM** [comment]
And its merged. I wont publish a new release *yet* because of the "broken" language picker I am waiting on @sk22 to fix

**Comment by florian-obernberger** [comment]
Nice!

Yeah, don't worry, I hope it'll be fixed soon!

**Pull request merged**
