### PR TITLE
feat(about): try to open links in-app

### PR DESCRIPTION
**Pull request by FineFindus**
The About screen often contains links the local accounts (e.g. moderators, admins) instead of always opening them in the browser, try to open them in-app first.

### CODE REVIEW

**Comment by LucasGGamerM** [comment]
Is this really how it should be done? Isn´t there a mastodon link detector thingy in UiUtils for exactly that?

**Comment by FineFindus** [comment]
Yeah, after thinking about it a bit, we should be able to just always use UiUtils.openURL, since it will fallback to the web browser anyways :)

**Comment by LucasGGamerM** [comment]
Looks great!

**Comment by LucasGGamerM** [comment]
Looks great!

**Pull request merged**
