### PR TITLE
Fix empty hashtag as search result for '@' query for Pleroma

### PR DESCRIPTION
**Pull request by Xen4n**
For unknown reasons Pleroma server responses with empty hashtag `SearchResult`. Therefore, the client crashes when try to set an empty title resource (because of empty title) to a TextView during ListItem bind.
So we just filter empty hashtag before it comes to the ViewModel.
<details><summary>Screenshot</summary>
<p>

image

</p>
</details>

### CODE REVIEW

**Comment by LucasGGamerM** [comment]
Don't mix the PR's. Make a separate one for the other fix

**Comment by Xen4n** [comment]
I didn't know that my commit would automatically go into the PR. How to remove second commit?

**Comment by LucasGGamerM** [comment]
You should drop the second commit and then force push it to your repo

**Comment by Xen4n** [comment]
Should I do "Reset Current Branch to previous commit"? Or another way?

**Comment by LucasGGamerM** [comment]
No, you should right click on the commits you wanna remove, and click 'Drop commits'

**Comment by Xen4n** [comment]
Drop commits is unavailable for me in Android Studio. So 'Revert commits' done. Is it ok?

**Comment by LucasGGamerM** [comment]
> Drop commits is unavailable for me in Android Studio. So 'Revert commits' done. Is it ok?

Mkay, so just reset the branch to the hashtag fix commit, and then force push

**Comment by Xen4n** [comment]
I found why I couldn't drop commit. Because of protection on master branch.

**Comment by LucasGGamerM** [comment]
I did it successfully on my end. No need to worry now

**Pull request merged**
